AllCops:
  TargetRubyVersion: 2.6
Style/FrozenStringLiteralComment:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/AbcSize:
  Max: 30
Metrics/ParameterLists:
  Max: 10
Metrics/MethodLength:
  Max: 40
Metrics/BlockLength:
  Max: 50
Metrics/LineLength:
  Max: 240
Naming/MethodParameterName:
  Enabled: false
