AllCops:
  TargetRubyVersion: 2.5
Style/FrozenStringLiteralComment:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/AbcSize:
  Max: 30
Metrics/ParameterLists:
  Max: 10
Metrics/MethodLength:
  Max: 20
Metrics/BlockLength:
  Max: 50
Metrics/LineLength:
  Max: 160
Naming/UncommunicativeMethodParamName:
  Enabled: false
