require 'ffi'
require 'pry'

require_relative 'raylib/helpers'
require_relative 'raylib/types'
require_relative 'raylib/constants'
require_relative 'raylib/structs'
require_relative 'raylib/functions'
require_relative 'raylib/ruby'
require_relative 'raylib/version'
