inherit_from: ../.rubocop.yml

Metrics/AbcSize:
  Max: 120
Metrics/CyclomaticComplexity:
  Max: 24
Metrics/PerceivedComplexity:
  Max: 28
Metrics/ClassLength:
  Max: 400
Metrics/BlockLength:
  Max: 200
Style/NumericPredicate:
  Enabled: false
